"use client";
import { AddButton } from "@/components/Buttons/AddButton";
import { SearchInput } from "@/components/Buttons/InputSearch";
import { CompanyTable } from "@/components/tables/CompanyTable";
import { SearchInspectionTable } from "@/components/tables/SearchInspectionTable";
import { TAB_HEADER } from "@/styles/assets";
import { useRouter } from "next/navigation";
import { useState } from "react";

const Companies = () => {
  const router = useRouter();

const searchInspectionData = [
  {
    id: 'INSP-001',
    orderId: 'ORD-2024-001',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Assigned',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-002',
    orderId: 'ORD-2024-002',
   name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Completed',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-003',
    orderId: 'ORD-2024-003',
 name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'QA Review',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-004',
    orderId: 'ORD-2024-004',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Cancelled',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-005',
    orderId: 'ORD-2024-005',
     name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Rejected',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-006',
    orderId: 'ORD-2024-006',
     name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Assigned',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-007',
    orderId: 'ORD-2024-007',
   name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$23.45',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Assigned',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-008',
    orderId: 'ORD-2024-008',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'In Progress',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-009',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Pending',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-010',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'QA Review',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-011',
    orderId: 'ORD-2024-011',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Completed',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-012',
    orderId: 'ORD-2024-012',
   name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Completed',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-013',
    orderId: 'ORD-2024-013',
    name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'Cancelled',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
  {
    id: 'INSP-014',
    orderId: 'ORD-2024-014',
     name: 'Stave Rogers',
    policy: 'PL29045',
    dateRequested: '10/10/24',
    inspectionType: '10',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'MI',
    state: 'High',
    zip: '54901',
    clientCost: '$56.23',
    fieldRepComm: '$56.23',
    requestDate: '10/10/24',
    status: 'In Progress',
    actionView: true,
    actionDelete: true,
    actionEdit: true,
  },
];


  return (
    <>
      <div className=" w-full bg-medium-blue h-full p-5 rounded-[10px] flex flex-col gap-4">
<div className="flex w-full justify-between items-start lg:items-center flex-col lg:flex-row gap-4 lg:gap-0">
          <span className={TAB_HEADER}>Search Inspection</span>

        </div>
        <div>
          <SearchInspectionTable
            data={searchInspectionData}
            onView={(row:any) =>console.log(`${row.id}`)}
            onEdit={(row:any) =>console.log(`${row.id}`)}
            onDelete={(row:any) =>console.log(`${row.id}`)}
          />
        </div>
      </div>
    </>
  );
};

export default Companies;
